// Generated by CoffeeScript 1.3.3
(function() {

  describe("Public interface exists", function() {
    return it("defines the app", function() {
      return expect(SampleApp.app).toBeDefined();
    });
  });

}).call(this);
